apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-image
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: test-image
    spec:
      containers:
        - name:  test-image
          image: 514991545313.dkr.ecr.us-west-2.amazonaws.com/nuovonick/test-image:latest
          ports:
            - containerPort: 3000